packages:
  - 'packages/*'

catalog:
  typescript: ^5.3.0
  "@types/node": ^20.10.0
  dotenv: ^16.3.1
  "node-fetch": ^3.3.2
  "dotenv-cli": ^9.0.0
  tsx: ^4.6.0
  astro: ^5.11.0
  "@astrojs/react": ^4.3.0
  "@astrojs/sitemap": ^3.4.1
  "@astrojs/check": ^0.9.4
  "astro-i18n-aut": ^0.7.0
  react: ^19.1.0
  "react-dom": ^19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.0
  "@tailwindcss/typography": ^0.5.15
  "@tailwindcss/vite": ^4.1.11
  tailwindcss: ^4.1.11
  daisyui: ^4.12.14
  clsx: ^2.1.1
  "lucide-react": ^0.468.0
  sass: ^1.83.0